#!/bin/bash

A="`cat miner.cs`"
B="`cat Grid.cs`"
C="`cat Timer.cs`"
D="`cat Radio.cs`"
E="`cat Mover.cs`"
F="`cat Goto.cs`"
G="`cat ThrusterManager.cs`"
H="`cat Thruster.cs`"
I="`cat Gyroscope.cs`"
J="`cat Aligner.cs`"
K="`cat RemoteControl.cs`"
L="`cat FsmStateFactory.cs`"
M="`cat FsmState.cs`"
N="`cat FsmStateSub.cs`"
O="`cat FsmStateImplementation.cs`"
P="`cat FsmMemorySpace.cs`"
Q="`cat FsmInterpreter.cs`"
R="`cat Undock.cs`"
S="`cat Dock.cs`"
T="`cat RequestValueOverRadio.cs`"
U="`cat MoveBasic.cs`"
V="`cat goAbovePos.cs`"
V="`cat goAbovePos.cs`"
W="`cat goAboveMyPos.cs`"
X="`cat DockPlanetary.cs`"
Y="`cat ProtoStack.cs`"
Z="`cat DockBasic.cs`"
A1="`cat Proto.cs`"
A2="`cat ProtoRcv.cs`"
A3="`cat RadioMsg.cs`"
A4="`cat Recharge.cs`"
echo "$A" "$B" "$C" "$D" "$E" "$F" "$G" "$H" "$I" "$J" "$K" "$L" "$M" "$N" "$O" "$P" "$Q" "$R" "$S" "$T" "$U" "$V" "$W" "$X" "$Y" "$Z" "$A1" "$A2" "$A3" "$A4" > /dev/clipboard

